version: '3.9'

services:
  oracle-db:
    image: gvenzl/oracle-free:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - APP_USER=${APP_USER}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
    ports:
      - "${ORACLE_PORT}:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "tnsping", "FREEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  oracle_data:
