--------------------------------------------------------
--  File created - Friday-October-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REF_SWI_LS_INTEREST_BK
--------------------------------------------------------

  CREATE TABLE "ODS"."REF_SWI_LS_INTEREST_BK" 
   (	"SWI_LS_CONTRACT_ID" NUMBER, 
	"SWI_LS_MPESA_INTEREST" NUMBER, 
	"SWI_LS_BANK_INTEREST" NUMBER, 
	"SWI_LS_DATE" DATE, 
	"SWI_LS_GROSS_CUSTOMER_INTEREST" NUMBER
   ) ;

   COMMENT ON COLUMN "ODS"."REF_SWI_LS_INTEREST_BK"."SWI_LS_CONTRACT_ID" IS 'Contract ID';
   COMMENT ON COLUMN "ODS"."REF_SWI_LS_INTEREST_BK"."SWI_LS_MPESA_INTEREST" IS 'Interest Generated By M-PESA';
   COMMENT ON COLUMN "ODS"."REF_SWI_LS_INTEREST_BK"."SWI_LS_BANK_INTEREST" IS 'Interest Generated By the Bank';
   COMMENT ON COLUMN "ODS"."REF_SWI_LS_INTEREST_BK"."SWI_LS_GROSS_CUSTOMER_INTEREST" IS 'GROSS Interest Generated By the customer';
--------------------------------------------------------
--  Constraints for Table REF_SWI_LS_INTEREST_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" MODIFY ("SWI_LS_CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" MODIFY ("SWI_LS_MPESA_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" MODIFY ("SWI_LS_BANK_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" MODIFY ("SWI_LS_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" MODIFY ("SWI_LS_GROSS_CUSTOMER_INTEREST" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_LS_INTEREST_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" ADD CONSTRAINT "REF_SWI_LS_INTEREST_BK_FK1" FOREIGN KEY ("SWI_LS_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;
