--------------------------------------------------------
--  File created - Friday-October-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REF_SWI_AUTOMATIC_PAYMENT_BK
--------------------------------------------------------

  CREATE TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" 
   (	"SWI_CONTRACT_ID" NUMBER, 
	"SWI_CUSTOMER_INTEREST" NUMBER, 
	"SWI_MPESA_INTEREST" NUMBER, 
	"SWI_BANK_INTEREST" NUMBER, 
	"SWI_TAX_PAID" NUMBER, 
	"SWI_TRANSACTION_ID" VARCHAR2(20), 
	"SWI_CREATED_AT" DATE, 
	"SWI_CUSTOMER_GROSS_INTEREST" NUMBER
   ) ;
--------------------------------------------------------
--  Constraints for Table REF_SWI_AUTOMATIC_PAYMENT_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_CUSTOMER_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_MPESA_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_BANK_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_TAX_PAID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" MODIFY ("SWI_CREATED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_AUTOMATIC_PAYMENT_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" ADD CONSTRAINT "REF_SWI_AUTOMATIC_PAYMENT_BK_CONTRACT_ID" FOREIGN KEY ("SWI_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;
