--------------------------------------------------------
--  File created - Friday-October-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REF_SWI_SAVINGS_CONTRACT
--------------------------------------------------------

  CREATE TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" 
   (	"SWI_ID" NUMBER, 
	"SWI_MSISDN" VARCHAR2(20), 
	"SWI_SAVING_TYPE" VARCHAR2(20), 
	"SWI_NORMAL_BALANCE" NUMBER, 
	"SWI_INTEREST_BALANCE" NUMBER DEFAULT 0, 
	"SWI_BANK_ID" NUMBER, 
	"SWI_INTEREST_LOST" NUMBER, 
	"SWI_MPESA_COMISSION" NUMBER DEFAULT 0, 
	"SWI_BANK_COMISSION" NUMBER DEFAULT 0, 
	"SWI_CONTRACT_STATE" VARCHAR2(20), 
	"SWI_SAVING_CREATION_DATE" DATE, 
	"SWI_EXPECTED_MATURITY_DATE" DATE, 
	"SWI_LAST_UPDATE" DATE, 
	"SWI_LAST_INTEREST_UPDATE" DATE, 
	"SWI_INTEREST_UPDATE_COUNTER" NUMBER DEFAULT 0, 
	"SWI_TAX_PAID" NUMBER DEFAULT 0, 
	"SWI_LANG" VARCHAR2(2) DEFAULT 'PT', 
	"SWI_FIRST_DAY" DATE, 
	"SWI_SUB_ID" VARCHAR2(50) DEFAULT NULL, 
	"SWI_NEXT_INTEREST_PAY" DATE
   ) ;

   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_ID" IS 'Contract ID For Internal Use';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_MSISDN" IS 'Customer MSIDN';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_SAVING_TYPE" IS 'Type of Saving
';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_NORMAL_BALANCE" IS 'Amount used to save';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_INTEREST_BALANCE" IS 'Earned Interest';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_BANK_ID" IS 'Bank ID
';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_INTEREST_LOST" IS 'Interest lost in case of withdrawal before maturity Date';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_MPESA_COMISSION" IS 'Earned Commission for Mpesa';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_BANK_COMISSION" IS 'Earned Commission for Bank';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_CONTRACT_STATE" IS 'State of the Saving Contract';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_LAST_INTEREST_UPDATE" IS 'Last Interest update';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_INTEREST_UPDATE_COUNTER" IS 'Counter of times that the interest was updated';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_TAX_PAID" IS 'Total Taxe paid';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_LANG" IS 'Contract Default Language';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_FIRST_DAY" IS 'First day of acumulative interest';
   COMMENT ON COLUMN "ODS"."REF_SWI_SAVINGS_CONTRACT"."SWI_SUB_ID" IS 'ID of GSM';
--------------------------------------------------------
--  DDL for Index REF_SWI_SAVINGS_CONTRACT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."REF_SWI_SAVINGS_CONTRACT_PK" ON "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table REF_SWI_SAVINGS_CONTRACT
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_MSISDN" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_SAVING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_NORMAL_BALANCE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_INTEREST_BALANCE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_BANK_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_MPESA_COMISSION" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_BANK_COMISSION" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_CONTRACT_STATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_SAVING_CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_EXPECTED_MATURITY_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" ADD CONSTRAINT "REF_SWI_SAVINGS_CONTRACT_PK" PRIMARY KEY ("SWI_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_FIRST_DAY" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" MODIFY ("SWI_SUB_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_SAVINGS_CONTRACT
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" ADD CONSTRAINT "REF_SWI_SAVINGS_CONTRACT_BANK_FK" FOREIGN KEY ("SWI_BANK_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_BANK" ("SWI_BANK_ID") ENABLE;
