--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_AUTOMATIC_PAYMENT_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_AUTOMATIC_PAYMENT_BK" ADD CONSTRAINT "REF_SWI_AUTOMATIC_PAYMENT_BK_CONTRACT_ID" FOREIGN KEY ("SWI_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_LS_INTEREST_BK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_LS_INTEREST_BK" ADD CONSTRAINT "REF_SWI_LS_INTEREST_BK_FK1" FOREIGN KEY ("SWI_LS_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Constraints for Table REF_SWI_SAVINGS_BANK
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_BANK_ID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_ANNUAL_INTEREST" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_MPESA_COMMISSION" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_BANK_COMMISSION" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" ADD CONSTRAINT "REF_SWI_SAVINGS_BANK_PK" PRIMARY KEY ("SWI_BANK_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_CUSTOMER_TAX" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_MPESA_CANCELATION_TAX" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_BANK_CANCELATION_TAX" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" ADD CONSTRAINT "REF_SWI_SAVINGS_BANK_SHORTCODE_UK" UNIQUE ("SWI_BANK_SHORTCODE")
  USING INDEX (CREATE UNIQUE INDEX "ODS"."REF_SWI_SAVINGS_BANK_UK1" ON "ODS"."REF_SWI_SAVINGS_BANK" ("SWI_BANK_SHORTCODE") 
  )  ENABLE;
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_BANK_SHORTCODE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."REF_SWI_SAVINGS_BANK" MODIFY ("SWI_CUSTOMER_COMMISSION" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_SAVINGS_CONTRACT
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_CONTRACT" ADD CONSTRAINT "REF_SWI_SAVINGS_CONTRACT_BANK_FK" FOREIGN KEY ("SWI_BANK_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_BANK" ("SWI_BANK_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_SAVINGS_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_TRANSACTIONS" ADD CONSTRAINT "REF_SWI_SAVINGS_TRANSACTIONS_FK1" FOREIGN KEY ("SWI_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table REF_SWI_SAVINGS_UPDATE_HISTORY
--------------------------------------------------------

  ALTER TABLE "ODS"."REF_SWI_SAVINGS_UPDATE_HISTORY" ADD CONSTRAINT "REF_SWI_DAYLY_UPDATE_HISTORY_FK1" FOREIGN KEY ("SWI_CONTRACT_ID")
	  REFERENCES "ODS"."REF_SWI_SAVINGS_CONTRACT" ("SWI_ID") ON DELETE CASCADE ENABLE;
